### ISSUE TITLE
点击商品详细 报错“出现异常”

### ISSUE THREAD

**Issue by Viennacacao** [huanghanzhilian/c-shopping-rn#2]
点击商品详细 报错“出现异常”
<img width="358" alt="image" src="https://github.com/huanghanzhilian/c-shopping-rn/assets/63215372/e7d8c28c-762e-4e8a-a80c-2d04cec658d8">

**Comment by huanghanzhilian** [comment]
您好，请修改下.env文件
```
EXPO_PUBLIC_BASE_URL=https://c-shopping-three.vercel.app
```

国内的服务器我还没有构建，晚点我修改下

**Comment by huanghanzhilian** [comment]
问题已经修改了

**Comment by Viennacacao** [comment]
好的
