### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Josemarsilvestre** [huanghanzhilian/c-shopping-rn#3]
I can't log in

**Comment by huanghanzhilian** [comment]
1. Please create a new .env file from .env.example file in the project root directory to define the required environment variables.
```
EXPO_PUBLIC_BASE_URL=https://c-shopping-three.vercel.app
```
2. Need to register an account first

Did you follow the above steps? I don't see this problem, can you tell me more?

**Comment by Josemarsilvestre** [comment]
thanks

**Comment by huanghanzhilian** [comment]
I found the issue and I've fixed it, thanks for your feedback.
