### ISSUE TITLE
本地启动显示没有权限

### ISSUE THREAD

**Issue by Hujianboo** [huanghanzhilian/c-shopping-rn#5]
[GraphQL] Entity not authorized: AccountEntity
这个大佬能帮忙看下为啥吗，是不是需要你帮加用户组之类的

**Comment by huanghanzhilian** [comment]
您好，我没有遇到这样的问题，您能描述清楚些吗？我好帮您解决。

**Comment by Hujianboo** [comment]
> 您好，我没有遇到这样的问题，您能描述清楚些吗？我好帮您解决。

![image](https://github.com/huanghanzhilian/c-shopping-rn/assets/17348813/e854abf2-33a9-470d-a74d-a1a484eb544c)
在yarn start这步，会出现这个问题。

**Comment by imesong** [comment]
[GraphQL] Entity not authorized: AccountEntity[29bd4c9f-cb90-4ded-b352-f4e98fee18a3] (viewer = RegularUserViewerContext[1b75a708-ab0c-4baa-915b-e153a820ba31], action = READ, ruleIndex = -1)

**Comment by imesong** [comment]
> [GraphQL] Entity not authorized: AccountEntity[29bd4c9f-cb90-4ded-b352-f4e98fee18a3] (viewer = RegularUserViewerContext[1b75a708-ab0c-4baa-915b-e153a820ba31], action = READ, ruleIndex = -1)

我也遇到了这个问题。iOS 设备，按照流程运行起来，使用iOS设备扫码。提示上面的错误。

**Comment by huanghanzhilian** [comment]
谢谢反馈，我晚上尝试复现解决下。

**Comment by rmd1710714107** [comment]
我也遇到这个问题了，Android设备，Android 12

**Comment by rmd1710714107** [comment]
已解决，具体可以参照这篇文章[[GraphQL] Entity not authorized error!](https://forums.expo.dev/t/graphql-entity-not-authorized-error/66122)
大体思路就是，去expo新建一个项目，然后把项目里的projectId、name和slug改成自己的

**Comment by Hujianboo** [comment]
> 已解决，具体可以参照这篇文章[[GraphQL] Entity not authorized error!](https://forums.expo.dev/t/graphql-entity-not-authorized-error/66122) 大体思路就是，去expo新建一个项目，然后把项目里的projectId、name和slug改成自己的

' 把项目里的projectId、name和slug改成自己的',方便讲的详细点吗。是自己的账号新建一个项目，然后把项目里的projectId换成c-shopping-rn的项目id吗还是

**Comment by rmd1710714107** [comment]
> > 已解决，具体可以参照这篇文章[[GraphQL] Entity not authorized error!](https://forums.expo.dev/t/graphql-entity-not-authorized-error/66122) 大体思路就是，去expo新建一个项目，然后把项目里的projectId、name和slug改成自己的
> 
> ' 把项目里的projectId、name和slug改成自己的',方便讲的详细点吗。是自己的账号新建一个项目，然后把项目里的projectId换成c-shopping-rn的项目id吗还是


修改步骤用代码表示如下：

用自己的账号在expo上新建一个项目，比如newProject
newProject.name=c-shopping-rn.name
newProject.name=c-shopping-rn.slug
创建成功后修改app.json里的内容
c-shopping-rn.projectId=newProject.projectId

**Comment by huanghanzhilian** [comment]
感谢大家的反馈，实在抱歉，我在本地构建的文件修改了配置（eas命令自动修改），导致大家无法本地跑起来，我先将这些依赖删除，后续我会把eas构建流程写在readme中。代码已经同步，大家看看还能跑起来吗？（测试过程我没有跑很多机器）。
